const products = [
  // ===== MENS =====
  {
    id: 1,
    name: "Foldpack No.1 Backpack",
    category: "mens",
    price: 200,
    actualprice: 300,
    rating: 4.5,
    count: 120,
    image: "./assets/mens_clothing/Foldpack_No1_Backpack.jpeg",
    description: "Your perfect pack for everyday use.",
  },
  {
    id: 2,
    name: "Mens Casual Premium Slim Fit T-Shirts",
    category: "mens",
    price: 220,
    actualprice: 400,
    rating: 4.1,
    count: 259,
    image: "./assets/mens_clothing/Slim_Fit_TShirts.jpeg",
    description: "Slim-fitting style, lightweight fabric.",
  },
  {
    id: 3,
    name: "Mens Cotton Jacket",
    category: "mens",
    price: 500,
    actualprice: 700,
    rating: 4.7,
    count: 500,
    image: "./assets/mens_clothing/cotton jacket.jpg",
    description: "Great outerwear for Spring/Autumn/Winter.",
  },
  {
    id: 4,
    name: "Men’s Denim Classic Shirt",
    category: "mens",
    price: 455,
    actualprice: 600,
    rating: 4.2,
    count: 340,
    image: "./assets/mens_clothing/Mens Casual Denim Shirt.webp",
    description: "Soft denim fabric, versatile for all occasions.",
  },
  {
    id: 5,
    name: "Men’s Chino Trousers",
    category: "mens",
    price: 600,
    actualprice: 800,
    rating: 4.3,
    count: 210,
    image: "./assets/mens_clothing/Training Joggers.jpeg",
    description: "Comfortable, stretchable fabric for daily wear.",
  },
  {
    id: 6,
    name: "Men’s Sports Track Pants",
    category: "mens",
    price: 500,
    actualprice: 900,
    rating: 4.6,
    count: 420,
    image: "./assets/mens_clothing/Men’s Sports Track Pants.jpg",
    description: "Ideal for workouts and casual outings.",
  },
  {
    id: 7,
    name: "Men’s Formal Watch",
    category: "mens",
    price: 400,
    actualprice: 700,
    rating: 4.4,
    count: 150,
    image: "./assets/mens_clothing/Leather Wrist Watch.jpeg",
    description: "Genuine polished buckle finish.",
  },
  {
    id: 8,
    name: "Men’s Running Sneakers",
    category: "mens",
    price: 699,
    actualprice: 1000,
    rating: 4.8,
    count: 370,
    image: "./assets/mens_clothing/running-sneakers.jpeg",
    description: "High grip sole, breathable mesh upper.",
  },
  {
    id: 9,
    name: "Men’s Wool Sweater",
    category: "mens",
    price: 499,
    actualprice: 700,
    rating: 4.7,
    count: 180,
    image: "./assets/mens_clothing/Men’s Wool Sweater.jpeg",
    description: "Soft wool blend for cozy winter days.",
  },
  {
    id: 10,
    name: "Men’s Classic Blazer",
    category: "mens",
    price: 1299,
    actualprice: 2000,
    rating: 4.9,
    count: 95,
    image: "./assets/mens_clothing/Men’s Classic Blazer.jpeg",
    description: "Tailored fit with modern design.",
  },

  // ===== WOMENS =====
  {
    id: 11,
    name: "Women’s Solid Short Sleeve Top",
    category: "womens",
    price: 399,
    actualprice: 600,
    rating: 4.5,
    count: 240,
    image: "./assets/women's clothing/Women’s Solid Short Sleeve Top.jpeg",
    description: "Soft cotton blend, perfect fit.",
  },
  {
    id: 12,
    name: "Women’s Windbreaker Jacket",
    category: "womens",
    price: 599,
    actualprice: 750,
    rating: 4.6,
    count: 275,
    image: "./assets/women's clothing/Windbreaker Jackett.jpeg",
    description: "Lightweight and comfortable.",
  },
  {
    id: 13,
    name: "Women’s Maxi Floral Dress",
    category: "womens",
    price: 750,
    actualprice: 999,
    rating: 4.7,
    count: 310,
    image: "./assets/women's clothing/Women’s Floral Maxi Dress.jpeg",
    description: "Beautiful summer dress with floral prints.",
  },
  {
    id: 14,
    name: "Women’s Skinny Jeans",
    category: "womens",
    price: 499,
    actualprice: 699,
    rating: 4.4,
    count: 190,
    image: "./assets/women's clothing/Women’s Skinny Jeans.jpeg",
    description: "Stretchable, high-waist denim for comfort.",
  },
  {
    id: 15,
    name: "Women’s Handbag Leather Tote",
    category: "womens",
    price: 899,
    actualprice: 1100,
    rating: 4.8,
    count: 420,
    image: "./assets/women's clothing/Women’s Leather Handbag.jpeg",
    description: "Elegant handbag with spacious compartments.",
  },
  {
    id: 16,
    name: "Women’s Ankle Boots",
    category: "womens",
    price: 700,
    actualprice: 999,
    rating: 4.9,
    count: 250,
    image: "./assets/women's clothing/Sports Running Shoes.jpeg",
    description: "Durable sole and stylish leather finish.",
  },
  {
    id: 17,
    name: "Women’s Cotton Kurti",
    category: "womens",
    price: 599,
    actualprice: 799,
    rating: 4.3,
    count: 280,
    image: "./assets/women's clothing/Women’s Cotton Kurti.jpeg",
    description: "Traditional yet modern casual wear.",
  },
  {
    id: 18,
    name: "Women’s Sports Leggings",
    category: "womens",
    price: 699,
    actualprice: 899,
    rating: 4.2,
    count: 350,
    image: "./assets/women's clothing/Women’s Sports Leggings.jpeg",
    description: "Stretchable and sweat-proof material.",
  },
  {
    id: 19,
    name: "Women’s Cardigan Sweater",
    category: "womens",
    price: 999,
    actualprice: 1299,
    rating: 4.6,
    count: 150,
    image: "./assets/women's clothing/Women’s Knit Cardigan.jpeg",
    description: "Soft knit for warmth and comfort.",
  },
  {
    id: 20,
    name: "Women’s Elegant Evening Gown",
    category: "womens",
    price: 1299,
    actualprice: 1999,
    rating: 4.8,
    count: 100,
    image: "./assets/women's clothing/Women’s Elegant Evening Gown.jpeg",
    description: "Elegant silk gown for special occasions.",
  },

  // ===== ELECTRONICS =====
  {
    id: 21,
    name: "WD 2TB Elements Hard Drive",
    category: "electronics",
    price: 999,
    actualprice: 1499,
    rating: 4.3,
    count: 310,
    image: "./assets/electronics/WD 2TB Elements Hard Drivee.jpeg",
    description: "USB 3.0, fast and reliable data storage.",
  },
  {
    id: 22,
    name: "Samsung 49-Inch Gaming Monitor",
    category: "electronics",
    price: 69999,
    actualprice: 85000,
    rating: 4.9,
    count: 150,
    image: "./assets/electronics/Samsung 49-Inch Gaming Monitorr.jpeg",
    description: "UltraWide curved gaming monitor.",
  },
  {
    id: 23,
    name: "Apple iPhone 14 Pro",
    category: "electronics",
    price: 130000,
    actualprice: 180000,
    rating: 4.8,
    count: 480,
    image: "./assets/electronics/Apple iPhone 14 Pro.jpeg",
    description: "Special features and long battery life.",
  },
  {
    id: 24,
    name: "Sony WH-1000XM5 Headphones",
    category: "electronics",
    price: 999,
    actualprice: 1499,
    rating: 4.9,
    count: 320,
    image: "./assets/electronics/Sony WH-1000XM5 Headphoness.jpeg",
    description: "Top-tier ANC with superior sound quality.",
  },
  {
    id: 25,
    name: "Logitech Wireless Mouse M720",
    category: "electronics",
    price: 499,
    actualprice: 799,
    rating: 4.4,
    count: 600,
    image: "./assets/electronics/Logitech MX Master 3 Mousee.jpeg",
    description: "Ergonomic, multi-device Bluetooth connectivity.",
  },
  {
    id: 26,
    name: "Apple Watch Series 9",
    category: "electronics",
    price: 1599,
    actualprice: 1999,
    rating: 4.7,
    count: 270,
    image: "./assets/electronics/Apple-Watch-Series-09.webp",
    description: "Track your fitness and stay connected.",
  },
  {
    id: 27,
    name: "JBL Bluetooth Speaker",
    category: "electronics",
    price: 1999,
    actualprice: 2499,
    rating: 4.5,
    count: 380,
    image: "./assets/electronics/JBL Charge 5 Bluetooth Speaker.jpeg",
    description: "Portable speaker with deep bass.",
  },
  {
    id: 28,
    name: "Canon DSLR Camera EOS 90D",
    category: "electronics",
    price: 9999,
    actualprice: 15999,
    rating: 4.8,
    count: 145,
    image: "./assets/electronics/Canon EOS 250D Camera.jpeg",
    description: "High-resolution camera for professionals.",
  },
  {
    id: 29,
    name: "Dell XPS 13 Laptop",
    category: "electronics",
    price: 60999,
    actualprice: 79999,
    rating: 4.9,
    count: 210,
    image: "./assets/electronics/Dell Inspiron 15 Laptop.jpeg",
    description: "Compact ultrabook with Intel i7 processor.",
  },
  {
    id: 30,
    name: "HP Wireless Keyboard Combo",
    category: "electronics",
    price: 499,
    actualprice: 699,
    rating: 4.4,
    count: 700,
    image: "./assets/electronics/HP Wireless Keyboard Combo.jpeg",
    description: "Smart HP Keyboard Combo with wireless connection.",
  },

  // ===== JEWELRY =====
  {
    id: 31,
    name: "Silver Legends Naga Ring",
    category: "jewelry",
    price: 695,
    actualprice: 890,
    rating: 4.8,
    count: 140,
    image: "./assets/jewelery/Silver Legends Naga Ring.jpeg",
    description: "Power ring inspired by mythical warriors.",
  },
  {
    id: 32,
    name: "Gold Plated Micropave Ring",
    category: "jewelry",
    price: 1000,
    actualprice: 1499,
    rating: 4.5,
    count: 76,
    image: "./assets/jewelery/Gold Plated Microwave Ring.jpeg",
    description: "Satisfaction guaranteed, return on exchange.",
  },
  {
    id: 33,
    name: "Diamond Stud Earrings",
    category: "jewelry",
    price: 899,
    actualprice: 1299,
    rating: 4.9,
    count: 120,
    image: "./assets/jewelery/Emerald Stud Earrings.jpeg",
    description: "Classic design, real diamond shine.",
  },
  {
    id: 34,
    name: "Pearl Earrings Set",
    category: "jewelry",
    price: 499,
    actualprice: 599,
    rating: 4.7,
    count: 200,
    image: "./assets/jewelery/Pearl Drop Earringss.jpeg",
    description: "Graceful design for elegant occasions.",
  },
  {
    id: 35,
    name: "Emerald Gold Bracelet",
    category: "jewelry",
    price: 35999,
    actualprice: 40000,
    rating: 4.8,
    count: 180,
    image: "./assets/jewelery/Rose Gold Infinity Bracelett.jpeg",
    description: "Elegant design with natural emerald stones.",
  },
  {
    id: 36,
    name: "Platinum Wedding Band",
    category: "jewelry",
    price: 5999,
    actualprice: 8000,
    rating: 5.0,
    count: 95,
    image: "./assets/jewelery/Platinum Wedding Band.jpeg",
    description: "Symbol of eternal love and strength.",
  },
  {
    id: 37,
    name: "Sterling Silver Leaf Pendant",
    category: "jewelry",
    price: 2500,
    actualprice: 3999,
    rating: 4.6,
    count: 130,
    image: "./assets/jewelery/Sterling Silver Leaf Pendant.jpeg",
    description: "Brilliant leaf set in sterling silver.",
  },
  {
    id: 38,
    name: "Ruby Cluster Ring",
    category: "jewelry",
    price: 49999,
    actualprice: 59999,
    rating: 4.7,
    count: 170,
    image: "./assets/jewelery/Ruby Cluster Ring.jpeg",
    description: "Delicate sapphire stones with gold finish.",
  },
  {
    id: 39,
    name: "Sapphire Charm Bracelet",
    category: "jewelry",
    price: 249,
    actualprice: 399,
    rating: 4.4,
    count: 210,
    image: "./assets/jewelery/Sapphire Charm Bracelet.jpeg",
    description: "Trendy piece with sparkling stones.",
  },
  {
    id: 40,
    name: "Diamond Heart Necklacee",
    category: "jewelry",
    price: 899,
    actualprice: 999,
    rating: 4.9,
    count: 75,
    image: "./assets/jewelery/Diamond Heart Necklacee.jpeg",
    description: "Royal look for traditional events.",
  },
];
